FROM node:20-alpine

RUN apk add --no-cache openssl postgresql-client

EXPOSE 3000

WORKDIR /app

ENV NODE_ENV=development

# Install dependencies including dev
COPY package.json package-lock.json ./
RUN npm ci

# Copy application